spring.application.name=spring-redis

# R2DBC (Reactive)
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/cereal_db
spring.r2dbc.username=normal
spring.r2dbc.password=0000

# JDBC (for migrations or blocking access)
spring.datasource.url=jdbc:postgresql://localhost:5432/cereal_db
spring.datasource.username=normal
spring.datasource.password=0000

# Redis
spring.redis.host=localhost
spring.redis.port=6379
